### ISSUE TITLE
order of inputs

### ISSUE THREAD

**Issue by JessAwBryant** [jmeppley/batch_launcher#2]
I just noticed that while running blastall with batch_launcher, you get the following error if the database  input isn't among the first few inputs (but if it is, then batch_launcher works just fine!):

eg.  python batch_launcher.py -N 100 -R 10 blastall -p blastx -db /path_to_database/blastdb -i /path_to_input/inputs.fasta -o /path_to_output/output.vs.Refseq75

error: 
 File "/slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py", line 2525, in <module>
    main()
  File "/slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py", line 551, in main
    options.taskType = checkCommand(cmdargs,sgeOptions,options)
  File "/slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py", line 841, in checkCommand
    inspectCommandForTaskType[taskType](command,taskType,sgeOptions,m.group%281%29,batchOptions)
  File "/slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py", line 2276, in inspectBlastCommand
    raise Exception("You must supply a database to run blastall")
Exception: You must supply a database to run blastall

**Comment by jmeppley** [comment]
Are you sure? I thought blastall usually takes just a -d, not -db. I think
it's the "blast plus" commands that take the -db flag.

**Comment by JessAwBryant** [comment]
hmm.. well at least that command didn't throw any errors (unlike previous
attempts), but based on qstat it doesn't look like the blast search has
started yet either?

full command:
python /slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py
 -- blastall -p blastx -db
/mnt/lysine/jmeppley/servers/galaxy/py-metagenomics/databases/blastdb/RefSeq/75/RefSeq-75.AllProteins.faa.ldb/blastdb
-i
/mnt/lysine/jbryant/DEEP_SEQUENCING/Vibrio/Vibrio_HOT236_1_1000_genes_johns_annotations.fasta
-o
/mnt/lysine/jbryant/DEEP_SEQUENCING/Vibrio/Vibrio_HOT236_1_1000_genes_johns_annotations.fasta.vs.Refseq75
-N 100 -R 10

**Comment by jmeppley** [comment]
Hmm. There is something wrong with batch_launcher. It is not reporting
errors well.

The command should look like this:
{batch_launcher} {batch_launcher arguments} -- {full command}

The "--" is key, and I think was missing from your first command. The
database error is a red herring, I think.

Try this:

python /slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py -N
100 -R 10 -- blastall -p blastx -d /mnt/lysine/jmeppley/servers/
galaxy/py-metagenomics/databases/blastdb/RefSeq/75/
RefSeq-75.AllProteins.faa.ldb/blastdb -i /mnt/lysine/jbryant/DEEP_
SEQUENCING/Vibrio/Vibrio_HOT236_1_1000_genes_johns_annotations.fasta -o
/mnt/lysine/jbryant/DEEP_SEQUENCING/Vibrio/Vibrio_HOT236_1_1000_genes_johns_
annotations.fasta.vs.Refseq75

-j

**Comment by JessAwBryant** [comment]
It didnt produce any errors, but the job has been queued for over an hour.

**Comment by jmeppley** [comment]
Sorry, Jess. To make matters worse, I'm now in HI, so there is a 6 hour
time difference.

For some reason, I had batch_launcher hard coded to a python binary that
didn't exist. I must have copied it over from a different machine. I've
tried to make it more intelligent about the python binary.

I have this command working:

python /slipstream/home/jmeppley/projects/batch_launcher/batch_launcher.py
-v -N 100 -R 10 -- blastall -p blastx -d
/mnt/lysine/jmeppley/servers/galaxy/py-metagenomics/databases/blastdb/RefSeq/75/RefSeq-75.AllProteins.faa.ldb/blastdb
-i
/mnt/lysine/jbryant/DEEP_SEQUENCING/Vibrio/Vibrio_HOT236_1_1000_genes_johns_annotations.fasta
-o /slipstream/home/jmeppley/tmp/test.out

I'll leave it running and you can pull the results from
/slipstream/home/jmeppley/tmp/test.out in the morning.

-j

**Comment by JessAwBryant** [comment]
Aloha John, I bet your jetlag will work in my favor for a little while at
least. ; )

Did your blast launcher run work? I'm not seeing test.out in
/slipstream/home/jmeppley/tmp/

**Comment by jmeppley** [comment]
It's working, but it's still running.

Also, I peeked at the partial output and it's in the verbose, default blast
format. EG:

BLASTX 2.2.25 [Feb-01-2011]

Reference: Altschul, Stephen F., Thomas L. Madden, Alejandro A. Schaffer,
Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997),
"Gapped BLAST and PSI-BLAST: a new generation of protein database search
programs",  Nucleic Acids Res. 25:3389-3402.

Query= HOT236_1_1000m_c1_1 # 30 # 2423 # 1 #
ID=1_1;partial=00;start_type=TTG;rbs_motif=GGA/GAG/AGG;rbs_spacer=5-
10bp;gc_cont=0.428
         (2394 letters)

Database: RefSeq/RefSeq-75/RefSeq-75.AllProteins.faa
           61,034,675 sequences; 23,386,816,845 total letters

Searching..................................................done

```
                                                             Score    E
```

Sequences producing significant alignments:                      (bits)
Value

gi|497286556|ref|WP_009600773.1| copper exporting ATPase [Vibrio...  1425
0.0

gi|493937315|ref|WP_006881602.1| copper exporting ATPase [Vibrio...   953
0.0

gi|940337531|ref|WP_054963272.1| copper-transporting ATPase [Vib...   947
0.0

gi|740361200|ref|WP_038197128.1| copper-transporting ATPase [Vib...   946
0.0

gi|740367766|ref|WP_038203233.1| copper-transporting ATPase [Vib...   944
0.0

gi|908713898|ref|WP_049845466.1| copper-transporting ATPase [Vib...   944
0.0

gi|762206305|ref|WP_043877091.1| copper-transporting ATPase [Vib...   941
0.0

gi|782703093|ref|WP_045612539.1| copper-transporting ATPase [Vib...   940
0.0

gi|800928359|ref|WP_045956917.1| copper-transporting ATPase [Vib...   939
0.0

gi|499390887|ref|WP_011078354.1| copper exporting ATPase [Vibrio...   937
0.0

> gi|497286556|ref|WP_009600773.1| copper exporting ATPase [Vibrio
>             caribbeanicus].
>           Length = 903

 Score = 1425 bits (3689), Expect = 0.0
 Identities = 743/797 (93%), Positives = 763/797 (95%)
 Frame = +1

Query: 1    LAKQSRIIETVESAGYKAVLDSHSLVTTTSKVPPEVPKKHENSCSPAVQPHETMNKIHLL 180
            LAKQ+RIIETVES GY+AVLDSHSL T TSKV PE P+K +NSCSP  QP+ETMNKIHLL
Sbjct: 107  LAKQNRIIETVESTGYQAVLDSHSLATPTSKVTPEAPQKQDNSCSPETQPNETMNKIHLL 166

Query: 181  ISGMTCASCVASVEKALLSLEPITSAQINLAENSAFITSKISKIELKNQLYQAVESAGYQ 360
            ISGMTCASCVASVEKALLSLEPITSAQINLAENSAFITSKISKIELKNQLYQAVESAGY+
Sbjct: 167  ISGMTCASCVASVEKALLSLEPITSAQINLAENSAFITSKISKIELKNQLYQAVESAGYR 226

Query: 361  AEYLDDISELEQKNLTQQQTEQTQHRKNAILGLAVGAPLMMWGILGGNMMIRNSQDQLAW 540
            AEYLD ISELEQKN+TQQQTEQTQH+KNAILGLAVGAPLMMWGILGGNMMIRNSQDQLAW
Sbjct: 227  AEYLDGISELEQKNITQQQTEQTQHKKNAILGLAVGAPLMMWGILGGNMMIRNSQDQLAW 286

Query: 541  GAIAILSFILLSTAGRYYFLNAWQALTHKRATMDTLVAIGTGAAWLYSTLVIISPTLFPV 720
            GAIAILSFILLSTAGRYYFLNAWQALTHKRATMDTLVA+GTGAAWLYSTLVIISPTLFP
Sbjct: 287  GAIAILSFILLSTAGRYYFLNAWQALTHKRATMDTLVAMGTGAAWLYSTLVIISPTLFPA 346

Query: 721  ISRHVYFEASAMIIGLISLGHYIESKAKAGTTRSIQALINLQPNTATHIINGVDKQINIE 900
            ISRHVYFEASAMIIGLISLGHYIESKAKAGTTRSIQALINLQPNTAT IINGVDK+INIE
Sbjct: 347  ISRHVYFEASAMIIGLISLGHYIESKAKAGTTRSIQALINLQPNTATQIINGVDKKINIE 406

Query: 901  DVLVGMQLRIKPGEKVPTDAVVISGVTYVDESMLTGESMPVVKKTGDKVAAGTLNQDGSL
1080
            DVLVGMQLRIKPGEKVPTDAVVISGVTYVDESMLTGESMPVVKKTGDKVAAGTLNQDGSL
Sbjct: 407  DVLVGMQLRIKPGEKVPTDAVVISGVTYVDESMLTGESMPVVKKTGDKVAAGTLNQDGSL 466

Query: 1081 VVEASSLGRDSLLSRIIELVRQAQSSKPKIAKLADQISAIFVPTVILIAGCSALVWYFFG
1260
            VVEASSLGRDSLLSRIIELVRQAQSSKPKIAKLADQISAIFVPTVILIA CSALVWY FG
Sbjct: 467  VVEASSLGRDSLLSRIIELVRQAQSSKPKIAKLADQISAIFVPTVILIACCSALVWYIFG 526

Query: 1261 PEPKLSYMLVVTTTVLIIACPCALGLATPLSVTAGIGKAAEMGILIRDADVLQTANNIDT
1440
            PEPKLSYMLVVTTTVLIIACPCALGLATPLSVTAGIGKAAEMGILIRDADVLQTANNIDT
Sbjct: 527  PEPKLSYMLVVTTTVLIIACPCALGLATPLSVTAGIGKAAEMGILIRDADVLQTANNIDT 586

Query: 1441 VVFDKTGTLTEGKPRVQKIYSFDYDQHELIKMAASVEQNSEHPLARAIVTEAKCDNLPKS
1620
            VVFDKTGTLTEGKP+VQKIYSF+YDQ+ELIKMAASVEQNSEHPLARAIVTEAKCDNLPKS
Sbjct: 587  VVFDKTGTLTEGKPQVQKIYSFNYDQYELIKMAASVEQNSEHPLARAIVTEAKCDNLPKS 646

Query: 1621 DSFYSLPGKGVFATIDHQSVAIVSSNYAREQQWSLAKAHNILNQCISKAWTPXXXXXXXX
1800
            D+FYSLPGKGVFATID QSVAIVSSNYAREQQWSL K H ILNQC SKAWTP
Sbjct: 647  DNFYSLPGKGVFATIDRQSVAIVSSNYAREQQWSLTKVHTILNQCTSKAWTPVVVAIEGQ 706

You probably would prefer a tabular format. I should have specified "-m 8"

-j

**Comment by JessAwBryant** [comment]
...oh  that's because its still running. I submitted 14K query sequences.
That isn't unreasonable correct?
1. (unrelated) Do you know that the difference is between the
   readpool.fastq and reads.raw.fastq files are in the MIRA assembly folders.

eg. /mnt/lysine/assemblies/HOT_standardized/HOT236_1_1000m

Mahalo!

**Comment by jmeppley** [comment]
Argument order wasn't the problem, but I have improved the interpreter situation
